### ISSUE TITLE
Hello Crossle, I need your help

### ISSUE THREAD

**Issue by FloridaStream** [shoutv/L10N#216]
The vitamio project is outdated, with many problems in OpenSSL in version 4.0 and 5.0, in addition to not receive updates or responses from the developers did not want to bother you opening this issue, but I have to ask.

You could not give an updated libs in the OpenSSL vitamio v4 and v5?

Or by chance could release the full source of vitamio 4.2.2 that I myself could always compile with all updates (ffmpeg, openssl, librtmp etc), I would commit myself to keep the source code strictly confidential if necessary.

I fear for a future where you can no longer pay attention to your project, and that it is lost.
I'm using version 4.2.

Thanks for attention @crossle and all vitamio.org team.

**Comment by crossle** [comment]
This is not vitamio issue place, please dont commit here

**Comment by FloridaStream** [comment]
Ok, sorry, you can delete this post now.
