### ISSUE TITLE
translate to  values-zh-rTW strings

### ISSUE THREAD

**Issue by xingstarx** [shoutv/L10N#320]
```xml
<string name="activity_landing_vk">使用 VK 登录</string>
<string name="activity_landing_email">使用 Email 注册</string>
<string name="activity_landing_google">使用 Google 登录</string>
<string name="activity_landing_facebook">使用 Facebook 登录</string>
<string name="activity_landing_twitter">使用 Twitter 登录</string>
<string name="activity_landing_phone">使用手机号登录</string>
<string name="activity_landing_sign_in_email">使用 Email 登录</string>
```

**Comment by xingstarx** [comment]
@LNDDYL  help translate the new android TW strings . thanks

**Comment by LNDDYL** [comment]
`<string name="activity_landing_vk">使用 VK 登登入</string>
<string name="activity_landing_email">使用 Email 註冊</string>
<string name="activity_landing_google">使用 Google 登入</string>
<string name="activity_landing_facebook">使用 Facebook 登入</string>
<string name="activity_landing_twitter">使用 Twitter 登录</string>
<string name="activity_landing_phone">使用手機號碼登入</string>
<string name="activity_landing_sign_in_email">使用 Email 登入</string>
`

**Comment by xingstarx** [comment]
thanks

**Comment by xingstarx** [comment]
@LNDDYL  帮忙看看这个地方，很久以前翻译的字符串 https://github.com/shoutv/L10N/pull/173
